# Generated by Django 3.2.6 on 2021-08-18 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0003_auto_20210819_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panier',
            options={'ordering': ['-nb']},
        ),
        migrations.RemoveField(
            model_name='panier',
            name='user',
        ),
        migrations.AddField(
            model_name='panier',
            name='nb',
            field=models.IntegerField(default=0, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='panier',
            name='price',
            field=models.FloatField(default=0, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='panier',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Numéro de panier'),
        ),
        migrations.RemoveField(
            model_name='panier',
            name='article',
        ),
        migrations.AddField(
            model_name='panier',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='total',
            field=models.FloatField(blank=True, verbose_name='Total'),
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Commande')),
                ('total', models.FloatField(blank=True, verbose_name='Total')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panier',
            },
        ),
        migrations.AlterField(
            model_name='panier',
            name='command',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.command', verbose_name='Commande'),
        ),
    ]
