# Generated by Django 3.2.6 on 2021-08-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20210819_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
