# Generated by Django 3.2.6 on 2021-08-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20210819_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Statu'},
        ),
        migrations.RemoveField(
            model_name='command',
            name='status',
        ),
        migrations.AddField(
            model_name='command',
            name='status',
            field=models.ManyToManyField(blank=True, default='Aucun', to='ecommerce.Status', verbose_name='Status'),
        ),
    ]
