# Generated by Django 3.2.6 on 2021-08-19 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0008_auto_20210819_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='user',
        ),
        migrations.AddField(
            model_name='command',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
