# Generated by Django 3.2.6 on 2021-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20210819_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='nb',
            field=models.PositiveIntegerField(verbose_name='Nombre'),
        ),
    ]
