# Generated by Django 3.2.6 on 2021-08-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_blogcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(null=True, to='posts.BlogCategory'),
        ),
    ]
