# Generated by Django 3.2.6 on 2021-08-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='avatar', verbose_name='Image'),
        ),
    ]
