# Generated by Django 3.2.6 on 2021-08-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_customuser_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='avatar', verbose_name='Avatar'),
        ),
    ]
